<?xml version="1.0" encoding="utf-8"?><Database Name="G:\WPF\Canvasser\Data.sdf" EntityNamespace="Canvasser" ContextNamespace="Canvasser" Class="CanvasserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Party" Member="Parties">
    <Type Name="Party">
      <Column Name="PartyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Colour" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="PollingDistrict" Member="PollingDistricts">
    <Type Name="PollingDistrict">
      <Column Name="PD" Type="System.String" DbType="NVarChar(2)" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(16)" CanBeNull="false" />
      <Column Name="ImprintName" Type="System.String" DbType="NVarChar(100)" CanBeNull="false" />
      <Column Name="ImprintAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="false" />
	  <Column Name="DisplayOrder" Type="System.Int16" DbType="smallint" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Elector" Member="Electors">
    <Type Name="Elector">
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Intention2012" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Postal2012" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ElectorId" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Voted2012" Type="System.Boolean" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Postal2013" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Intention2013" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Markers" Type="System.String" DbType="NVarChar(4)" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Voted2013" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Postal2014" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="Intention2014" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(100)" CanBeNull="false" />
      <Column Name="Voted2014" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="Postal2015" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="Intention2015" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true"/>
      <Column Name="PD" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="PN" Type="System.Int16" DbType="smallint" CanBeNull="true" />
      <Column Name="PNs" Type="System.Int16" DbType="smallint" CanBeNull="true" />
	  <Column Name="PDPrevious" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="PNPrevious" Type="System.Int16" DbType="smallint" CanBeNull="true" />
      <Column Name="PNsPrevious" Type="System.Int16" DbType="smallint" CanBeNull="true" />
      <Column Name="Voted2015" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="Voted2015Bye" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="Postal2016" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="Intention2016" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Voted2016" Type="System.Boolean" DbType="bit" CanBeNull="true" />
	    <Column Name="Postal2017" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="Intention2017" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Voted2017" Type="System.Boolean" DbType="bit" CanBeNull="true" />
	    <Column Name="Postal2018" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="Intention2018" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Voted2018" Type="System.Boolean" DbType="bit" CanBeNull="true" />
	    <Column Name="Postal2019" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="Intention2019" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="TargetVoter" Member="TargetVoters">
    <Type Name="TargetVoter">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PD" Type="System.String" DbType="NVarChar(2)" CanBeNull="false" />
      <Column Name="PN" Type="System.Int16" DbType="smallint" CanBeNull="false" />
      <Column Name="PNs" Type="System.Int16" DbType="smallint" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(100)" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(100)" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true"/>
      <Column Name="Voted" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>