#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canvasser
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="G:\\WPF\\Canvasser\\Data.sdf")]
	public partial class CanvasserDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertParty(Party instance);
    partial void UpdateParty(Party instance);
    partial void DeleteParty(Party instance);
    partial void InsertPollingDistrict(PollingDistrict instance);
    partial void UpdatePollingDistrict(PollingDistrict instance);
    partial void DeletePollingDistrict(PollingDistrict instance);
    partial void InsertElector(Elector instance);
    partial void UpdateElector(Elector instance);
    partial void DeleteElector(Elector instance);
    partial void InsertTargetVoter(TargetVoter instance);
    partial void UpdateTargetVoter(TargetVoter instance);
    partial void DeleteTargetVoter(TargetVoter instance);
    #endregion
		
		public CanvasserDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CanvasserDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CanvasserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CanvasserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Party> Parties
		{
			get
			{
				return this.GetTable<Party>();
			}
		}
		
		public System.Data.Linq.Table<PollingDistrict> PollingDistricts
		{
			get
			{
				return this.GetTable<PollingDistrict>();
			}
		}
		
		public System.Data.Linq.Table<Elector> Electors
		{
			get
			{
				return this.GetTable<Elector>();
			}
		}
		
		public System.Data.Linq.Table<TargetVoter> TargetVoters
		{
			get
			{
				return this.GetTable<TargetVoter>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Party : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PartyId;
		
		private string _Name;
		
		private System.Nullable<long> _Colour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPartyIdChanging(int value);
    partial void OnPartyIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnColourChanging(System.Nullable<long> value);
    partial void OnColourChanged();
    #endregion
		
		public Party()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartyId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PartyId
		{
			get
			{
				return this._PartyId;
			}
			set
			{
				if ((this._PartyId != value))
				{
					this.OnPartyIdChanging(value);
					this.SendPropertyChanging();
					this._PartyId = value;
					this.SendPropertyChanged("PartyId");
					this.OnPartyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colour", DbType="BigInt")]
		public System.Nullable<long> Colour
		{
			get
			{
				return this._Colour;
			}
			set
			{
				if ((this._Colour != value))
				{
					this.OnColourChanging(value);
					this.SendPropertyChanging();
					this._Colour = value;
					this.SendPropertyChanged("Colour");
					this.OnColourChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class PollingDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PD;
		
		private string _ShortName;
		
		private string _ImprintName;
		
		private string _ImprintAddress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPDChanging(string value);
    partial void OnPDChanged();
    partial void OnShortNameChanging(string value);
    partial void OnShortNameChanged();
    partial void OnImprintNameChanging(string value);
    partial void OnImprintNameChanged();
    partial void OnImprintAddressChanging(string value);
    partial void OnImprintAddressChanged();
    #endregion
		
		public PollingDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PD", DbType="NVarChar(2)", CanBeNull=false, IsPrimaryKey=true)]
		public string PD
		{
			get
			{
				return this._PD;
			}
			set
			{
				if ((this._PD != value))
				{
					this.OnPDChanging(value);
					this.SendPropertyChanging();
					this._PD = value;
					this.SendPropertyChanged("PD");
					this.OnPDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="NVarChar(16)", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this.OnShortNameChanging(value);
					this.SendPropertyChanging();
					this._ShortName = value;
					this.SendPropertyChanged("ShortName");
					this.OnShortNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImprintName", DbType="NVarChar(100)", CanBeNull=false)]
		public string ImprintName
		{
			get
			{
				return this._ImprintName;
			}
			set
			{
				if ((this._ImprintName != value))
				{
					this.OnImprintNameChanging(value);
					this.SendPropertyChanging();
					this._ImprintName = value;
					this.SendPropertyChanged("ImprintName");
					this.OnImprintNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImprintAddress", DbType="NVarChar(100)", CanBeNull=false)]
		public string ImprintAddress
		{
			get
			{
				return this._ImprintAddress;
			}
			set
			{
				if ((this._ImprintAddress != value))
				{
					this.OnImprintAddressChanging(value);
					this.SendPropertyChanging();
					this._ImprintAddress = value;
					this.SendPropertyChanged("ImprintAddress");
					this.OnImprintAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Elector : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PD2012;
		
		private System.Nullable<short> _PN2012;
		
		private string _FirstName;
		
		private string _Surname;
		
		private string _Address;
		
		private string _Intention2012;
		
		private System.Nullable<bool> _Postal2012;
		
		private string _Date;
		
		private int _ElectorId;
		
		private System.Nullable<bool> _Voted2012;
		
		private string _PD2013;
		
		private System.Nullable<short> _PN2013;
		
		private System.Nullable<bool> _Postal2013;
		
		private string _Intention2013;
		
		private string _Markers;
		
		private short _PNs2012;
		
		private short _PNs2013;
		
		private string _Notes;
		
		private System.Nullable<bool> _Voted2013;
		
		private string _PD2014;
		
		private System.Nullable<short> _PN2014;
		
		private System.Nullable<bool> _Postal2014;
		
		private string _Intention2014;
		
		private System.Nullable<short> _PNs2014;
		
		private string _Address2;
		
		private System.Nullable<bool> _Voted2014;
		
		private string _PD2015;
		
		private System.Nullable<short> _PN2015;
		
		private System.Nullable<short> _PNs2015;
		
		private System.Nullable<bool> _Postal2015;
		
		private string _Intention2015;
		
		private string _Telephone;
		
		private string _PD;
		
		private System.Nullable<short> _PN;
		
		private System.Nullable<short> _PNs;
		
		private System.Nullable<bool> _Voted2015;
		
		private System.Nullable<bool> _Voted2015Bye;
		
		private System.Nullable<bool> _Postal2016;
		
		private string _Intention2016;
		
		private string _Postcode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPD2012Changing(string value);
    partial void OnPD2012Changed();
    partial void OnPN2012Changing(System.Nullable<short> value);
    partial void OnPN2012Changed();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnIntention2012Changing(string value);
    partial void OnIntention2012Changed();
    partial void OnPostal2012Changing(System.Nullable<bool> value);
    partial void OnPostal2012Changed();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnElectorIdChanging(int value);
    partial void OnElectorIdChanged();
    partial void OnVoted2012Changing(System.Nullable<bool> value);
    partial void OnVoted2012Changed();
    partial void OnPD2013Changing(string value);
    partial void OnPD2013Changed();
    partial void OnPN2013Changing(System.Nullable<short> value);
    partial void OnPN2013Changed();
    partial void OnPostal2013Changing(System.Nullable<bool> value);
    partial void OnPostal2013Changed();
    partial void OnIntention2013Changing(string value);
    partial void OnIntention2013Changed();
    partial void OnMarkersChanging(string value);
    partial void OnMarkersChanged();
    partial void OnPNs2012Changing(short value);
    partial void OnPNs2012Changed();
    partial void OnPNs2013Changing(short value);
    partial void OnPNs2013Changed();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnVoted2013Changing(System.Nullable<bool> value);
    partial void OnVoted2013Changed();
    partial void OnPD2014Changing(string value);
    partial void OnPD2014Changed();
    partial void OnPN2014Changing(System.Nullable<short> value);
    partial void OnPN2014Changed();
    partial void OnPostal2014Changing(System.Nullable<bool> value);
    partial void OnPostal2014Changed();
    partial void OnIntention2014Changing(string value);
    partial void OnIntention2014Changed();
    partial void OnPNs2014Changing(System.Nullable<short> value);
    partial void OnPNs2014Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnVoted2014Changing(System.Nullable<bool> value);
    partial void OnVoted2014Changed();
    partial void OnPD2015Changing(string value);
    partial void OnPD2015Changed();
    partial void OnPN2015Changing(System.Nullable<short> value);
    partial void OnPN2015Changed();
    partial void OnPNs2015Changing(System.Nullable<short> value);
    partial void OnPNs2015Changed();
    partial void OnPostal2015Changing(System.Nullable<bool> value);
    partial void OnPostal2015Changed();
    partial void OnIntention2015Changing(string value);
    partial void OnIntention2015Changed();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnPDChanging(string value);
    partial void OnPDChanged();
    partial void OnPNChanging(System.Nullable<short> value);
    partial void OnPNChanged();
    partial void OnPNsChanging(System.Nullable<short> value);
    partial void OnPNsChanged();
    partial void OnVoted2015Changing(System.Nullable<bool> value);
    partial void OnVoted2015Changed();
    partial void OnVoted2015ByeChanging(System.Nullable<bool> value);
    partial void OnVoted2015ByeChanged();
    partial void OnPostal2016Changing(System.Nullable<bool> value);
    partial void OnPostal2016Changed();
    partial void OnIntention2016Changing(string value);
    partial void OnIntention2016Changed();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    #endregion
		
		public Elector()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PD2012", DbType="NVarChar(2)", UpdateCheck=UpdateCheck.Never)]
		public string PD2012
		{
			get
			{
				return this._PD2012;
			}
			set
			{
				if ((this._PD2012 != value))
				{
					this.OnPD2012Changing(value);
					this.SendPropertyChanging();
					this._PD2012 = value;
					this.SendPropertyChanged("PD2012");
					this.OnPD2012Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN2012", DbType="smallint", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> PN2012
		{
			get
			{
				return this._PN2012;
			}
			set
			{
				if ((this._PN2012 != value))
				{
					this.OnPN2012Changing(value);
					this.SendPropertyChanging();
					this._PN2012 = value;
					this.SendPropertyChanged("PN2012");
					this.OnPN2012Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intention2012", DbType="NVarChar(16)", UpdateCheck=UpdateCheck.Never)]
		public string Intention2012
		{
			get
			{
				return this._Intention2012;
			}
			set
			{
				if ((this._Intention2012 != value))
				{
					this.OnIntention2012Changing(value);
					this.SendPropertyChanging();
					this._Intention2012 = value;
					this.SendPropertyChanged("Intention2012");
					this.OnIntention2012Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postal2012", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> Postal2012
		{
			get
			{
				return this._Postal2012;
			}
			set
			{
				if ((this._Postal2012 != value))
				{
					this.OnPostal2012Changing(value);
					this.SendPropertyChanging();
					this._Postal2012 = value;
					this.SendPropertyChanged("Postal2012");
					this.OnPostal2012Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(16)", UpdateCheck=UpdateCheck.Never)]
		public string Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElectorId", AutoSync=AutoSync.OnInsert, IsPrimaryKey=true, IsDbGenerated=true)]
		public int ElectorId
		{
			get
			{
				return this._ElectorId;
			}
			set
			{
				if ((this._ElectorId != value))
				{
					this.OnElectorIdChanging(value);
					this.SendPropertyChanging();
					this._ElectorId = value;
					this.SendPropertyChanged("ElectorId");
					this.OnElectorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voted2012", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> Voted2012
		{
			get
			{
				return this._Voted2012;
			}
			set
			{
				if ((this._Voted2012 != value))
				{
					this.OnVoted2012Changing(value);
					this.SendPropertyChanging();
					this._Voted2012 = value;
					this.SendPropertyChanged("Voted2012");
					this.OnVoted2012Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PD2013", DbType="NVarChar(2)", UpdateCheck=UpdateCheck.Never)]
		public string PD2013
		{
			get
			{
				return this._PD2013;
			}
			set
			{
				if ((this._PD2013 != value))
				{
					this.OnPD2013Changing(value);
					this.SendPropertyChanging();
					this._PD2013 = value;
					this.SendPropertyChanged("PD2013");
					this.OnPD2013Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN2013", DbType="smallint", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> PN2013
		{
			get
			{
				return this._PN2013;
			}
			set
			{
				if ((this._PN2013 != value))
				{
					this.OnPN2013Changing(value);
					this.SendPropertyChanging();
					this._PN2013 = value;
					this.SendPropertyChanged("PN2013");
					this.OnPN2013Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postal2013", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> Postal2013
		{
			get
			{
				return this._Postal2013;
			}
			set
			{
				if ((this._Postal2013 != value))
				{
					this.OnPostal2013Changing(value);
					this.SendPropertyChanging();
					this._Postal2013 = value;
					this.SendPropertyChanged("Postal2013");
					this.OnPostal2013Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intention2013", DbType="NVarChar(16)", UpdateCheck=UpdateCheck.Never)]
		public string Intention2013
		{
			get
			{
				return this._Intention2013;
			}
			set
			{
				if ((this._Intention2013 != value))
				{
					this.OnIntention2013Changing(value);
					this.SendPropertyChanging();
					this._Intention2013 = value;
					this.SendPropertyChanged("Intention2013");
					this.OnIntention2013Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Markers", DbType="NVarChar(4)", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Markers
		{
			get
			{
				return this._Markers;
			}
			set
			{
				if ((this._Markers != value))
				{
					this.OnMarkersChanging(value);
					this.SendPropertyChanging();
					this._Markers = value;
					this.SendPropertyChanged("Markers");
					this.OnMarkersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNs2012", DbType="smallint", UpdateCheck=UpdateCheck.Never)]
		public short PNs2012
		{
			get
			{
				return this._PNs2012;
			}
			set
			{
				if ((this._PNs2012 != value))
				{
					this.OnPNs2012Changing(value);
					this.SendPropertyChanging();
					this._PNs2012 = value;
					this.SendPropertyChanged("PNs2012");
					this.OnPNs2012Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNs2013", DbType="smallint", UpdateCheck=UpdateCheck.Never)]
		public short PNs2013
		{
			get
			{
				return this._PNs2013;
			}
			set
			{
				if ((this._PNs2013 != value))
				{
					this.OnPNs2013Changing(value);
					this.SendPropertyChanging();
					this._PNs2013 = value;
					this.SendPropertyChanged("PNs2013");
					this.OnPNs2013Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(4000)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voted2013", DbType="Bit")]
		public System.Nullable<bool> Voted2013
		{
			get
			{
				return this._Voted2013;
			}
			set
			{
				if ((this._Voted2013 != value))
				{
					this.OnVoted2013Changing(value);
					this.SendPropertyChanging();
					this._Voted2013 = value;
					this.SendPropertyChanged("Voted2013");
					this.OnVoted2013Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PD2014", DbType="NVarChar(2)")]
		public string PD2014
		{
			get
			{
				return this._PD2014;
			}
			set
			{
				if ((this._PD2014 != value))
				{
					this.OnPD2014Changing(value);
					this.SendPropertyChanging();
					this._PD2014 = value;
					this.SendPropertyChanged("PD2014");
					this.OnPD2014Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN2014", DbType="smallint")]
		public System.Nullable<short> PN2014
		{
			get
			{
				return this._PN2014;
			}
			set
			{
				if ((this._PN2014 != value))
				{
					this.OnPN2014Changing(value);
					this.SendPropertyChanging();
					this._PN2014 = value;
					this.SendPropertyChanged("PN2014");
					this.OnPN2014Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postal2014", DbType="bit")]
		public System.Nullable<bool> Postal2014
		{
			get
			{
				return this._Postal2014;
			}
			set
			{
				if ((this._Postal2014 != value))
				{
					this.OnPostal2014Changing(value);
					this.SendPropertyChanging();
					this._Postal2014 = value;
					this.SendPropertyChanged("Postal2014");
					this.OnPostal2014Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intention2014", DbType="NVarChar(16)")]
		public string Intention2014
		{
			get
			{
				return this._Intention2014;
			}
			set
			{
				if ((this._Intention2014 != value))
				{
					this.OnIntention2014Changing(value);
					this.SendPropertyChanging();
					this._Intention2014 = value;
					this.SendPropertyChanged("Intention2014");
					this.OnIntention2014Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNs2014", DbType="smallint")]
		public System.Nullable<short> PNs2014
		{
			get
			{
				return this._PNs2014;
			}
			set
			{
				if ((this._PNs2014 != value))
				{
					this.OnPNs2014Changing(value);
					this.SendPropertyChanging();
					this._PNs2014 = value;
					this.SendPropertyChanged("PNs2014");
					this.OnPNs2014Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(100)", CanBeNull=false)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voted2014", DbType="bit")]
		public System.Nullable<bool> Voted2014
		{
			get
			{
				return this._Voted2014;
			}
			set
			{
				if ((this._Voted2014 != value))
				{
					this.OnVoted2014Changing(value);
					this.SendPropertyChanging();
					this._Voted2014 = value;
					this.SendPropertyChanged("Voted2014");
					this.OnVoted2014Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PD2015", DbType="NVarChar(2)")]
		public string PD2015
		{
			get
			{
				return this._PD2015;
			}
			set
			{
				if ((this._PD2015 != value))
				{
					this.OnPD2015Changing(value);
					this.SendPropertyChanging();
					this._PD2015 = value;
					this.SendPropertyChanged("PD2015");
					this.OnPD2015Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN2015", DbType="smallint")]
		public System.Nullable<short> PN2015
		{
			get
			{
				return this._PN2015;
			}
			set
			{
				if ((this._PN2015 != value))
				{
					this.OnPN2015Changing(value);
					this.SendPropertyChanging();
					this._PN2015 = value;
					this.SendPropertyChanged("PN2015");
					this.OnPN2015Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNs2015", DbType="smallint")]
		public System.Nullable<short> PNs2015
		{
			get
			{
				return this._PNs2015;
			}
			set
			{
				if ((this._PNs2015 != value))
				{
					this.OnPNs2015Changing(value);
					this.SendPropertyChanging();
					this._PNs2015 = value;
					this.SendPropertyChanged("PNs2015");
					this.OnPNs2015Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postal2015", DbType="bit")]
		public System.Nullable<bool> Postal2015
		{
			get
			{
				return this._Postal2015;
			}
			set
			{
				if ((this._Postal2015 != value))
				{
					this.OnPostal2015Changing(value);
					this.SendPropertyChanging();
					this._Postal2015 = value;
					this.SendPropertyChanged("Postal2015");
					this.OnPostal2015Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intention2015", DbType="NVarChar(16)")]
		public string Intention2015
		{
			get
			{
				return this._Intention2015;
			}
			set
			{
				if ((this._Intention2015 != value))
				{
					this.OnIntention2015Changing(value);
					this.SendPropertyChanging();
					this._Intention2015 = value;
					this.SendPropertyChanged("Intention2015");
					this.OnIntention2015Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(12)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PD", DbType="NVarChar(2)")]
		public string PD
		{
			get
			{
				return this._PD;
			}
			set
			{
				if ((this._PD != value))
				{
					this.OnPDChanging(value);
					this.SendPropertyChanging();
					this._PD = value;
					this.SendPropertyChanged("PD");
					this.OnPDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN", DbType="smallint")]
		public System.Nullable<short> PN
		{
			get
			{
				return this._PN;
			}
			set
			{
				if ((this._PN != value))
				{
					this.OnPNChanging(value);
					this.SendPropertyChanging();
					this._PN = value;
					this.SendPropertyChanged("PN");
					this.OnPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNs", DbType="smallint")]
		public System.Nullable<short> PNs
		{
			get
			{
				return this._PNs;
			}
			set
			{
				if ((this._PNs != value))
				{
					this.OnPNsChanging(value);
					this.SendPropertyChanging();
					this._PNs = value;
					this.SendPropertyChanged("PNs");
					this.OnPNsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voted2015", DbType="bit")]
		public System.Nullable<bool> Voted2015
		{
			get
			{
				return this._Voted2015;
			}
			set
			{
				if ((this._Voted2015 != value))
				{
					this.OnVoted2015Changing(value);
					this.SendPropertyChanging();
					this._Voted2015 = value;
					this.SendPropertyChanged("Voted2015");
					this.OnVoted2015Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voted2015Bye", DbType="bit")]
		public System.Nullable<bool> Voted2015Bye
		{
			get
			{
				return this._Voted2015Bye;
			}
			set
			{
				if ((this._Voted2015Bye != value))
				{
					this.OnVoted2015ByeChanging(value);
					this.SendPropertyChanging();
					this._Voted2015Bye = value;
					this.SendPropertyChanged("Voted2015Bye");
					this.OnVoted2015ByeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postal2016", DbType="bit")]
		public System.Nullable<bool> Postal2016
		{
			get
			{
				return this._Postal2016;
			}
			set
			{
				if ((this._Postal2016 != value))
				{
					this.OnPostal2016Changing(value);
					this.SendPropertyChanging();
					this._Postal2016 = value;
					this.SendPropertyChanged("Postal2016");
					this.OnPostal2016Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intention2016", DbType="NVarChar(16)")]
		public string Intention2016
		{
			get
			{
				return this._Intention2016;
			}
			set
			{
				if ((this._Intention2016 != value))
				{
					this.OnIntention2016Changing(value);
					this.SendPropertyChanging();
					this._Intention2016 = value;
					this.SendPropertyChanged("Intention2016");
					this.OnIntention2016Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(8)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class TargetVoter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _PD;
		
		private short _PN;
		
		private short _PNs;
		
		private string _FirstName;
		
		private string _Surname;
		
		private string _Address;
		
		private string _Address2;
		
		private string _Telephone;
		
		private bool _Voted;
		
		private string _Notes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPDChanging(string value);
    partial void OnPDChanged();
    partial void OnPNChanging(short value);
    partial void OnPNChanged();
    partial void OnPNsChanging(short value);
    partial void OnPNsChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnVotedChanging(bool value);
    partial void OnVotedChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public TargetVoter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PD", DbType="NVarChar(2)", CanBeNull=false)]
		public string PD
		{
			get
			{
				return this._PD;
			}
			set
			{
				if ((this._PD != value))
				{
					this.OnPDChanging(value);
					this.SendPropertyChanging();
					this._PD = value;
					this.SendPropertyChanged("PD");
					this.OnPDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN", DbType="smallint")]
		public short PN
		{
			get
			{
				return this._PN;
			}
			set
			{
				if ((this._PN != value))
				{
					this.OnPNChanging(value);
					this.SendPropertyChanging();
					this._PN = value;
					this.SendPropertyChanged("PN");
					this.OnPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNs", DbType="smallint")]
		public short PNs
		{
			get
			{
				return this._PNs;
			}
			set
			{
				if ((this._PNs != value))
				{
					this.OnPNsChanging(value);
					this.SendPropertyChanging();
					this._PNs = value;
					this.SendPropertyChanged("PNs");
					this.OnPNsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(100)", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(100)", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(100)", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(100)", CanBeNull=false)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(12)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voted", DbType="bit")]
		public bool Voted
		{
			get
			{
				return this._Voted;
			}
			set
			{
				if ((this._Voted != value))
				{
					this.OnVotedChanging(value);
					this.SendPropertyChanging();
					this._Voted = value;
					this.SendPropertyChanged("Voted");
					this.OnVotedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(100)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
